service: flashcards-app-backend

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: ca-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
          Resource: 'arn:aws:s3:::${self:custom.bucket}/*'

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
          cors: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}

custom:
  bucket: ${file(env.yml):BUCKET}-${opt:stage, 'dev'}
